services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tiktokdb
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ../uploads:/app/uploads
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - database
volumes:
  db_data:

